// File generated by Firebase Flutter SDK. Configuração para Android e iOS.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// `dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// `
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJncfY83tmHerhBWVPDKAZia1538ycAy8',
    appId: '1:945698899262:android:c1cd7b86e2807a8e9b586f',
    messagingSenderId: '945698899262',
    projectId: 'estofariapro',
    storageBucket: 'estofariapro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlP3k_b-mocIzsJIfsvx1Mmj34uqSdhCI',
    appId: '1:945698899262:ios:5cd3c326d76e6d169b586f',
    messagingSenderId: '945698899262',
    projectId: 'estofariapro',
    storageBucket: 'estofariapro.firebasestorage.app',
    androidClientId: '945698899262-c1e22sq2bu0f3ff81lbcoijpit0gb7cn.apps.googleusercontent.com',
    iosClientId: '945698899262-c1e22sq2bu0f3ff81lbcoijpit0gb7cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.estofariaproApp',
  );
}
