// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClfWbcsaQdbX6UV3x1u8DJtS0PiDYgBpo',
    appId: '1:945698899262:web:e8ba68c0e4f2d8299b586f',
    messagingSenderId: '945698899262',
    projectId: 'estofariapro',
    authDomain: 'estofariapro.firebaseapp.com',
    storageBucket: 'estofariapro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJncfY83tmHerhBWVPDKAZia1538ycAy8',
    appId: '1:945698899262:android:428eb4ccc25635649b586f',
    messagingSenderId: '945698899262',
    projectId: 'estofariapro',
    storageBucket: 'estofariapro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlP3k_b-mocIzsJIfsvx1Mmj34uqSdhCI',
    appId: '1:945698899262:ios:5cd3c326d76e6d169b586f',
    messagingSenderId: '945698899262',
    projectId: 'estofariapro',
    storageBucket: 'estofariapro.firebasestorage.app',
    iosClientId: '945698899262-c1e22sq2bu0f3ff81lbcoijpit0gb7cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.estofariaproApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlP3k_b-mocIzsJIfsvx1Mmj34uqSdhCI',
    appId: '1:945698899262:ios:5cd3c326d76e6d169b586f',
    messagingSenderId: '945698899262',
    projectId: 'estofariapro',
    storageBucket: 'estofariapro.firebasestorage.app',
    iosClientId: '945698899262-c1e22sq2bu0f3ff81lbcoijpit0gb7cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.estofariaproApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClfWbcsaQdbX6UV3x1u8DJtS0PiDYgBpo',
    appId: '1:945698899262:web:99c9d004141dece99b586f',
    messagingSenderId: '945698899262',
    projectId: 'estofariapro',
    authDomain: 'estofariapro.firebaseapp.com',
    storageBucket: 'estofariapro.firebasestorage.app',
  );
}
