import 'package:flutter/material.dart';

final ColorScheme lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF8F4C33),
  onPrimary: Colors.white,
  primaryContainer: Color(0xFFFFDBCF),
  onPrimaryContainer: Color(0xFF72361E),
  secondary: Color(0xFF8E4C32),
  onSecondary: Colors.white,
  secondaryContainer: Color(0xFFFFDBCE),
  onSecondaryContainer: Color(0xFF71361D),
  tertiary: Color(0xFF8B4F25),
  onTertiary: Colors.white,
  tertiaryContainer: Color(0xFFFFDBC7),
  onTertiaryContainer: Color(0xFF6E380F),
  error: Color(0xFFBA1A1A),
  onError: Colors.white,
  errorContainer: Color(0xFFFFDAD6),
  onErrorContainer: Color(0xFF93000A),
  background: Color(0xFFFFF8F6),
  onBackground: Color(0xFF231A16),
  surface: Color(0xFFF9FAEF),
  onSurface: Color(0xFF1A1D16),
  surfaceVariant: Color(0xFFF5DED6),
  onSurfaceVariant: Color(0xFF53433E),
  outline: Color(0xFF85736D),
);

final ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFFFB59A),
  onPrimary: Color(0xFF55200A),
  primaryContainer: Color(0xFF72361E),
  onPrimaryContainer: Color(0xFFFFDBCF),
  secondary: Color(0xFFFFB599),
  onSecondary: Color(0xFF552009),
  secondaryContainer: Color(0xFF71361D),
  onSecondaryContainer: Color(0xFFFFDBCE),
  tertiary: Color(0xFFFFB688),
  onTertiary: Color(0xFF512400),
  tertiaryContainer: Color(0xFF6E380F),
  onTertiaryContainer: Color(0xFFFFDBC7),
  error: Color(0xFFFFB4AB),
  onError: Color(0xFF690005),
  errorContainer: Color(0xFF93000A),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF1A110E),
  onBackground: Color(0xFFF1DFD9),
  surface: Color(0xFF11140E),
  onSurface: Color(0xFFE2E3D9),
  surfaceVariant: Color(0xFF53433E),
  onSurfaceVariant: Color(0xFFD8C2BA),
  outline: Color(0xFFA08D86),
);
